  spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.gpxgptnvrabnyldtxtru&password=E0CKItyOKCseQATb
      driver-class-name: org.postgresql.Driver